export enum CODES {
  FAIL = 'FAIL',
  SUCCESS = 'SUCCESS',
  GET_THING_FAIL = 'GET_THING_FAIL',
  GET_CHEST_FAIL = 'GET_CHEST_FAIL',
  GET_THINGS_FAIL = 'GET_THINGS_FAIL',
  GET_CHESTS_FAIL = 'GET_CHESTS_FAIL',
  CREATE_PASSKEY_FAIL = 'CREATE_PASSKEY_FAIL',
  DELETE_PASSKEY_FAIL = 'DELETE_PASSKEY_FAIL',
  GET_PASSKEY_FOR_USER_FAIL = 'GET_PASSKEY_FOR_USER_FAIL',
  AUTH_FAIL_WRONG_CREDENTIAL = 'AUTH_FAIL_WRONG_CREDENTIAL',
}